### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by moshekaplan** [d33tah/afl-sid-repo#1]
When I run `docker run -ti d33tah/afl-sid` on my Ubuntu 16.04 x86, it downloads the files for the docker container and when it attempts to launch the container, displays the following error:

> FATA[0000] Error response from daemon: Cannot start container 11b1fc0eb7981af5dd2697290edc151903c1c34428077a358d7b2bae196acf87: [8] System error: exec format error

**Comment by d33tah** [comment]
@moshekaplan: why did you close it?

**Comment by moshekaplan** [comment]
I thought this was the wrong repo for this ticket and resubmitted it here: https://github.com/d33tah/aflize/issues/1 . I apologize if that was incorrect. Either way, I have not solved this issue.
